MakeMate-main/apps/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import main_page, signup, logout_page

app_name = "common"

urlpatterns = [
    path("", main_page, name="main_page"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", logout_page, name="logout"),
]

MakeMate-main/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("group/", include("apps.group.urls")),
    path("group_admin/", include("apps.groupAdmin.urls")),
    path("setting/", include("apps.groupSetting.urls")),
    path("preresult/", include("apps.preresult.urls")),
    path("result/", include("apps.result.urls")),
    path("idea/", include("apps.idea.urls")),
    path("vote/", include("apps.vote.urls")),
]

MakeMate-main/apps/common/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None
    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()

    def __str__(self):
        return self.username

MakeMate-main/apps/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1', 'password2', 'email']

MakeMate-main/apps/common/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.utils import timezone
from .models import User
from .forms import UserForm
from apps.group.models import Group, MemberState, AdminState, Vote


# Create your views here.
def main_page(request):
    if request.user.is_authenticated:
        user = request.user
        ##운영진인 모임 가져오기
        admin_groups = Group.objects.filter(admin_states__user=user)
        ##비운영진인 모임 가져오기
        # member_state&admin_state 둘다 존재시 admin_state를 우선으로
        member_set = set(Group.objects.filter(member_states__user=user))
        admin_set = set(admin_groups)
        member_groups = list(member_set - admin_set)
    
        ctx = {
            "admin_groups": admin_groups,
            "member_groups": member_groups,
        }
        # 운영진인 그룹내 멤버수
        admin_group_count = member_count(admin_groups)
        ctx["admin_group_count"] = admin_group_count
        # 비운영진 그룹내 멤버수
        member_group_count = member_count(member_groups)
        ctx["member_group_count"] = member_group_count
        return render(request, "common/index.html", ctx)
    else:
        return render(request, "common/index.html")


# 그룹별 인원수 count함수
def member_count(groups):
    member = []
    for group in groups:
        admin_states = set(
            AdminState.objects.filter(group=group).values_list("user",
                                                               flat=True))
        member_states = set(
            MemberState.objects.filter(group=group).values_list("user",
                                                                flat=True))
        states = admin_states.union(member_states)
        member.append({
            "group_name": group.title,
            "count": len(states),
        })
    return member


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("common:main_page")
    else:
        form = UserForm()
    ctx = {"form": form}
    return render(request, "common/signup.html", ctx)


def logout_page(request):
    logout(request)
    return redirect("common:main_page")

MakeMate-main/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>Home</a>
        <h3 class="title_content">로그인</h3>
    </div>
    <form method='post' action={% url 'common:login' %} class="wrap_form" autocomplete="off" novalidate>
        {% csrf_token %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
        <div class="form_highlight_content">
            {{ error }}
        </div>
        {% endfor %}
        <div class="inner_form">
            <label for='username'>아이디</label>
            <input id='username' type='text' name='username' value='{{ form.username.value|default_if_none:''}}'>
            <!-- 필드 오류 -->
            {% if form.username.errors %}
            <div class="form_highlight_content">
                {{ form.username.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form">
            <label for='password'>비밀번호</label>
            <input id='password' type='password' name='password' value='{{ form.password.value|default_if_none:''}}'>
            <!-- 필드 오류 -->
            {% if form.password.errors %}
            <div class="form_highlight_content">
                {{ form.password.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form_button">
            <button type='submit' class='primary_button_fill'>로그인</button>
            <input type="hidden" name="next" value="{{ next }}" />
        </div>
    </form>
</section>
{% endblock %}

MakeMate-main/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>Home</a>
        <h3 class="title_content">회원가입</h3>
    </div>
    <form method='POST' class="wrap_form" autocomplete="off" novalidate>
        {% csrf_token %}
        <!-- 넌필드 오류 -->
        {% for error in form.non_field_errors %}
            <div>
                <span class="form_highlight_content">{{ error }}</span>
            </div>
        {% endfor %}
        <div class="inner_form">
            <label>아이디 <i class="form_highlight_content">*</i></label>
            <div>{{form.username}}</div>
            <!-- 필드 오류 -->
            {% if form.username.errors %}
            <div class="form_highlight_content">
                {{ form.username.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form">
            <label>비밀번호 <i class="form_highlight_content">*</i></label>
            <div>{{form.password1}}</div>
            <!-- 필드 오류 -->
            {% if form.password1.errors %}
            <div class="form_highlight_content">
                {{ form.password1.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form">
            <label>비밀번호 확인 <i class="form_highlight_content">*</i></label>
            <div>{{form.password2}}</div>
            <!-- 필드 오류 -->
            {% if form.password2.errors %}
            <div class="form_highlight_content">
                {{ form.password2.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form">
            <label>이메일 주소 <i class="form_highlight_content">*</i></label>
            <div>{{form.email}}</div>
            <!-- 필드 오류 -->
            {% if form.email.errors %}
            <div class="form_highlight_content">
                {{ form.email.errors }}
            </div>
            {% endif %}
        </div>
        <div class="inner_form_button">
            <button type='submit' class="primary_button_fill">Join</button>
        </div>
    </form>
</section>
{% endblock %}