MakeMate-main/apps/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import main_page, signup, logout_page

app_name = "common"

urlpatterns = [
    path("", main_page, name="main_page"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", logout_page, name="logout"),
]

MakeMate-main/apps/groupSetting/urls.py
from django.urls import path
from .views import *

app_name = "group_setting"

urlpatterns = [
    path("base_set/", group_base_info, name="base_set"),
    path("<int:group_id>/password_check/",
         check_nonadmin,
         name="check_nonadmin"),
    path("<int:group_id>/admin/password_check/",
         check_admin,
         name="check_admin"),
    path("<int:group_id>/non_admin_info/", info_nonadmin,
         name="info_nonadmin"),
    path("share/<int:group_id>", group_share, name="share"),
]

MakeMate-main/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("group/", include("apps.group.urls")),
    path("group_admin/", include("apps.groupAdmin.urls")),
    path("setting/", include("apps.groupSetting.urls")),
    path("preresult/", include("apps.preresult.urls")),
    path("result/", include("apps.result.urls")),
    path("idea/", include("apps.idea.urls")),
    path("vote/", include("apps.vote.urls")),
]

MakeMate-main/templates/setting/setting_basic.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>back</a>
        <div class="inner_title">
            <h3 class="title_content">모임 개설</h3>
            <span id="state_desc">STEP 1. 기본 정보 작성</span>
        </div>
    </div>
    <div>
        <form action="{% url 'group_setting:base_set' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <div id="form_container">
            {% for field in form %}
                <div>
                    <p>{{ field.label }} <i class="form_highlight_content">*</i></p>
                    {{ field }}
                </div>
            {% endfor %}
            </div>
        </form>
    </div>
    <div class="inner_form_button">
        <a id="base_set_submit_btn" class="btn">다음</a>
    </div>
</section>
<script src="{% static 'js/group_info.js' %}"></script>
{% endblock %}

MakeMate-main/templates/setting/setting_sharing.html
{% extends 'base.html' %}

{% block content %}
<section> 
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>back</a>
        <div class="inner_title">
            <span class='setting_group_share_title'>모임 개설</span>
            <span class='setting_step4'>STEP 4. 모임 공유</span>
        </div>
    </div>
    <div class='setting_wrap_main_content'>
        <div class='card_contents_green'>모임 개설이 완료되었습니다!</div>
        <div class='setting_inner_url_txt'>
            <div>공유 링크</div>
            <div class='card_contents_green'>링크를 사용하여 구성원과 모임을 공유할 수 있습니다.</div>
        </div>
        <div class="group_member_url">
            <div>참여자 링크</div>
            <span>https://www.piromakemate.shop{% url 'group_setting:check_nonadmin' group.id %}</span>
            <div>비밀번호 : {{group.password}}</div>
        </div>
        <div class="group_admin_url">
            <div>운영자 링크 </div>
            <span>https://www.piromakemate.shop{% url 'group_setting:check_admin' group.id %}</span>
            <div>비밀번호 : {{group.password}}</div>
        </div>
    </div>
    <div class="common_inner_btn">
        <button class="primary_button"><a href="{% url 'common:main_page' %}">홈으로</a></button>
    </div>
</section>
{% endblock %}