MakeMate-main/apps/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import main_page, signup, logout_page

app_name = "common"

urlpatterns = [
    path("", main_page, name="main_page"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", logout_page, name="logout"),
]

MakeMate-main/apps/group/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "group"

urlpatterns = [    
    path("<int:group_id>/", group_detail, name="group_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

MakeMate-main/apps/groupSetting/urls.py
from django.urls import path
from .views import *

app_name = "group_setting"

urlpatterns = [
    path("base_set/", group_base_info, name="base_set"),
    path("<int:group_id>/password_check/",
         check_nonadmin,
         name="check_nonadmin"),
    path("<int:group_id>/admin/password_check/",
         check_admin,
         name="check_admin"),
    path("<int:group_id>/non_admin_info/", info_nonadmin,
         name="info_nonadmin"),
    path("share/<int:group_id>", group_share, name="share"),
]

MakeMate-main/apps/idea/urls.py
from django.urls import path
from .views import *

app_name = "idea"

urlpatterns = [
    path("<int:group_id>/create/", idea_create, name="idea_create"),
    path("<int:group_id>/modify/<int:idea_id>/",
         idea_modify,
         name="idea_modify"),
    path("<int:group_id>/delete/<int:idea_id>/",
         idea_delete,
         name="idea_delete"),
    path("<int:group_id>/detail/<int:idea_id>/",
         idea_detail,
         name="idea_detail"),
    path(
        "<int:group_id>/download/<int:idea_id>/",
        idea_download,
        name="idea_download",
    ),
]

MakeMate-main/apps/result/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = "result"

urlpatterns = [
    path("<int:group_id>/", result, name="result"),
    path("<int:group_id>/team_building/",
         start_team_building,
         name="team_building"),
]

MakeMate-main/apps/vote/urls.py
from django.urls import path
from .views import *

app_name = "vote"

urlpatterns = [
    path("<int:group_id>/idea_vote/", vote_create, name="vote_create"),
    path("<int:group_id>/idea_modify/", vote_modify, name="vote_modify"),
]

MakeMate-main/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("group/", include("apps.group.urls")),
    path("group_admin/", include("apps.groupAdmin.urls")),
    path("setting/", include("apps.groupSetting.urls")),
    path("preresult/", include("apps.preresult.urls")),
    path("result/", include("apps.result.urls")),
    path("idea/", include("apps.idea.urls")),
    path("vote/", include("apps.vote.urls")),
]

MakeMate-main/apps/group/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.files.storage import FileSystemStorage
from apps.common.models import User


class Group(models.Model):
    title = models.CharField("그룹 이름", max_length=30)
    password = models.CharField("그룹 비밀번호", max_length=15)
    ability_description1 = models.CharField("실력1 설명",
                                            max_length=100,
                                            null=True,
                                            blank=True)
    ability_description2 = models.CharField("실력2 설명",
                                            max_length=100,
                                            null=True,
                                            blank=True)
    ability_description3 = models.CharField("실력3 설명",
                                            max_length=100,
                                            null=True,
                                            blank=True)
    ability_description4 = models.CharField("실력4 설명",
                                            max_length=100,
                                            null=True,
                                            blank=True)
    ability_description5 = models.CharField("실력5 설명",
                                            max_length=100,
                                            null=True,
                                            blank=True)
    is_first_end = models.BooleanField(default=False)
    is_second_end = models.BooleanField(default=False)
    is_third_end = models.BooleanField(default=False)
    first_end_date = models.DateTimeField(default=timezone.now().date() +
                                          timezone.timedelta(days=1))
    second_end_date = models.DateTimeField(default=timezone.now().date() +
                                           timezone.timedelta(days=2))
    third_end_date = models.DateTimeField(default=timezone.now().date() +
                                          timezone.timedelta(days=3))

    def __str__(self):
        return self.title


class Idea(models.Model):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              null=True,
                              related_name="idea_member_states")
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField("아이디어 이름", max_length=31, null=True)
    intro = models.CharField("아이디어 한 줄 소개", max_length=50, null=True)
    file = models.FileField("첨부파일",
                            upload_to="ideas/files/%Y/%m/%d/",
                            null=True,
                            blank=True)
    content = models.TextField("아이디어 설명", max_length=1000, default="기본 설명")
    score = models.IntegerField("아이디어 점수", default=0)
    member = models.ManyToManyField(User,
                                    related_name="idea_member",
                                    blank=True)
    votes = models.IntegerField(default=0)

    ##선택된거 추가
    is_selected = models.BooleanField(default=False)
    ##2차선택
    second_selected = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class MemberState(models.Model):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              related_name="member_states")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group_ability = models.PositiveIntegerField(
        "실력",
        validators=[MaxValueValidator(5),
                    MinValueValidator(1)],
        null=True)

    idea_vote1 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote1_set",
                                   null=True,
                                   blank=True)
    idea_vote2 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote2_set",
                                   null=True,
                                   blank=True)
    idea_vote3 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote3_set",
                                   null=True,
                                   blank=True)
    idea_vote4 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote4_set",
                                   null=True,
                                   blank=True)
    idea_vote5 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote5_set",
                                   null=True,
                                   blank=True)
    idea_vote6 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote6_set",
                                   null=True,
                                   blank=True)
    idea_vote7 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote7_set",
                                   null=True,
                                   blank=True)
    idea_vote8 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote8_set",
                                   null=True,
                                   blank=True)
    idea_vote9 = models.ForeignKey(Idea,
                                   on_delete=models.SET_NULL,
                                   related_name="idea_vote9_set",
                                   null=True,
                                   blank=True)
    idea_vote10 = models.ForeignKey(Idea,
                                    on_delete=models.SET_NULL,
                                    related_name="idea_vote10_set",
                                    null=True,
                                    blank=True)
    my_team_idea = models.ForeignKey(
        Idea,
        on_delete=models.CASCADE,
        related_name="my_team_idea_set",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.user.username


class AdminState(models.Model):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              related_name="admin_states")
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Vote(models.Model):
    group = models.ForeignKey(Group,
                              on_delete=models.CASCADE,
                              related_name="votes")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idea_vote1 = models.ForeignKey(Idea,
                                   on_delete=models.CASCADE,
                                   related_name="vote1_set")
    idea_vote2 = models.ForeignKey(Idea,
                                   on_delete=models.CASCADE,
                                   related_name="vote2_set")
    idea_vote3 = models.ForeignKey(Idea,
                                   on_delete=models.CASCADE,
                                   related_name="vote3_set")

    def __str__(self):
        return f"Vote by {self.user.username} for {self.group.title}"

MakeMate-main/apps/result/models.py
from django.db import models

# Create your models here.

MakeMate-main/apps/group/views.py
from enum import Enum
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Group, MemberState, AdminState, Idea

# 유저 상태를 저장하는 ENUM
class State(Enum):
    NO_HISTORY = 0
    WITH_HISTORY = 1
    ADMIN = 2

class TeamNumber(Enum):
    THIRD_TEAM = 5
    SECOND_TEAM = 5
    FIRST_TEAM = 10

# Create your views here.
def redirect_by_auth(user, group_id):
    user_state = MemberState.objects.filter(user=user,
                                            group_id=group_id).first()

    admin_state = AdminState.objects.filter(user=user,
                                            group_id=group_id).first()

    if admin_state:
        return State.ADMIN
    
    if user_state:
        if user_state.group_ability is None:
            return State.NO_HISTORY
        else:
            return State.WITH_HISTORY

    return State.NO_HISTORY

@login_required(login_url="common:login")
def group_detail(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    author_ideas = Idea.objects.filter(group=group, author=request.user)
    other_ideas = Idea.objects.filter(group=group).exclude(author=request.user)
    user_state = MemberState.objects.filter(user=request.user, group=group).first()
    has_voted = False
    
    ideas_votes = {}
    if user_state:
        
        ideas_votes["idea_vote1_id"] = user_state.idea_vote1_id
        ideas_votes["idea_vote2_id"] = user_state.idea_vote2_id
        ideas_votes["idea_vote3_id"] = user_state.idea_vote3_id
        ideas_votes["idea_vote4_id"] = user_state.idea_vote4_id
        ideas_votes["idea_vote5_id"] = user_state.idea_vote5_id
        ideas_votes["idea_vote6_id"] = user_state.idea_vote6_id
        ideas_votes["idea_vote7_id"] = user_state.idea_vote7_id
        ideas_votes["idea_vote8_id"] = user_state.idea_vote8_id
        ideas_votes["idea_vote9_id"] = user_state.idea_vote9_id
        ideas_votes["idea_vote10_id"] = user_state.idea_vote10_id

        if (user_state.idea_vote1 or user_state.idea_vote2 or user_state.idea_vote3 or user_state.idea_vote4 or user_state.idea_vote5 or user_state.idea_vote6 or user_state.idea_vote7 or user_state.idea_vote8 or user_state.idea_vote9 or user_state.idea_vote10):
            has_voted = True

        # idea를 지망 순서로 정렬
        def sort_by_vote_rank(idea):
            if idea.id == ideas_votes["idea_vote1_id"]:
                return 1
            elif idea.id == ideas_votes["idea_vote2_id"]:
                return 2
            elif idea.id == ideas_votes["idea_vote3_id"]:
                return 3
            elif idea.id == ideas_votes["idea_vote4_id"]:
                return 4
            elif idea.id == ideas_votes["idea_vote5_id"]:
                return 5
            elif idea.id == ideas_votes["idea_vote6_id"]:
                return 6
            elif idea.id == ideas_votes["idea_vote7_id"]:
                return 7
            elif idea.id == ideas_votes["idea_vote8_id"]:
                return 8
            elif idea.id == ideas_votes["idea_vote9_id"]:
                return 9
            elif idea.id == ideas_votes["idea_vote10_id"]:
                return 10
            else:
                return 11  # 1, 2, 3지망이 아닌 아이디어는 4순위로
            
        if has_voted:
            other_ideas = sorted(other_ideas, key=sort_by_vote_rank)

        ctx = {
            "group": group,
            "author_ideas": author_ideas,
            "other_ideas": other_ideas,
            "ideas_votes": ideas_votes,
            "has_voted": has_voted,
            "user_state": user_state
        }
        return render(request, "group/group_detail.html", ctx)
    else:
        return redirect('/')

MakeMate-main/templates/group/group_admin_certification.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>Home</a>
        <div class="inner_title">
            <h3 class="title_content">{{group.title}}</h3>
            <span class="subtitle_content">그룹 가입하기 (운영자)</span>
        </div>
    </div>
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div class="form_highlight_content">
        {{ error }}
    </div>
    {% endfor %}
    <form method='post' action={% url 'group_setting:check_admin' group_id=group.id %} class="wrap_form" novalidate>
        {% csrf_token %}
        <div class="inner_form">
            <label>비밀번호를 입력해주세요.</label>
            <div>{{form.password}}</div>
            <!-- 필드 오류 -->
            {% if is_wrong %}
            <div class="form_highlight_content">
                비밀번호가 일치하지 않습니다. 다시 입력해주세요.
            </div>
            {% endif %}
        </div>
        <button type='submit' class='primary_button_fill'>그룹 가입</button>
    </form>
 
</section>
{% endblock %}

MakeMate-main/templates/group/group_detail.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
{% now "Y-m-d H:i:s" as current_time %}
<section>
    <div class="group_detail_header_container">
        <div class="wrap_title">
          <a href="{% url 'common:main_page' %}" class="home_btn">Home</a>
          <div class="inner_title">
            <h3 class="title_content">{{group.title}}</h3>
          </div>
        </div>
        
        {% if group.first_end_date|date:"Y-m-d H:i:s" > current_time %}
        <span class="subtitle_content">원하는 아이디어 10개에 투표해주세요. 자신의 아이디어를 추가할 수도 있습니다.</span>
        <div>1차 투표 마감까지 남은 시간</div>
        <div class='group_endtime' data-group-time='{{group.first_end_date.isoformat}}'></div>
        {% elif group.second_end_date|date:"Y-m-d H:i:s" > current_time %}
        <span class="subtitle_content">원하는 아이디어 5개에 투표해주세요. 자신의 아이디어를 추가할 수도 있습니다.</span>
        
        <div>2차 투표 마감까지 남은 시간</div>
        <div class='group_endtime' data-group-time='{{group.second_end_date.isoformat}}'></div>
        {% else %}
        <span class="subtitle_content">원하는 아이디어 3개에 투표해주세요. 팀 배정에 지망 순위도 반영됩니다.</span>
        
        <div>3차 투표 마감까지 남은 시간</div>
        <div class='group_endtime' data-group-time='{{group.third_end_date.isoformat}}'></div>                                 
        {% endif %}


      <div class="group_detail_btns">
        {% if has_voted %}
          {% if group.second_end_date|date:"Y-m-d H:i:s" <= current_time %}
          <button class="secondary_button"><a href="{% url 'vote:vote_modify' group_id=group.id %}" class="btn">투표 수정</a></button>
          {% else %}
          <button class="secondary_button"><a href="{% url 'vote:vote_create' group_id=group.id %}" class="btn">투표 수정</a></button>
          {% endif %}
        {% else %}
          <button class="secondary_button"><a href="{% url 'vote:vote_create' group_id=group.id %}" class="btn">투표하기</a></button>
        {% endif %}
    
        {% if not author_ideas %}
          {% if group.first_end_date|date:"Y-m-d H:i:s" > current_time %}
          <button class="primary_button"><a href="{% url 'idea:idea_create' group_id=group.id %}" class="btn">아이디어 추가</a></button>
          {% endif %}
        {% else %}
          {% for idea in author_ideas %}
          <button class="primary_button"><a href="{% url 'idea:idea_modify' group_id=group.id idea_id=idea.id %}" class="btn">아이디어 수정</a></button>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  
    {% if author_ideas %}
    <h2>나의 아이디어</h2>
    <div class="group_detail_my_idea">
      {% for idea in author_ideas %}
      <div class="wrap_card">
        <div class="group_detail_idea_desc">
          <h3><a href="{% url 'idea:idea_detail' group_id=group.id idea_id=idea.id %}">{{ idea.title }}</a></h3>
          <p>{{ idea.intro }}</p>
          <span>{{idea.author}}</span>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %} 
    
    {% if other_ideas %}
    <h2>투표</h2>
    <div class="group_detail_idea">
      {% for idea in other_ideas %}
      {% if group.second_end_date|date:"Y-m-d H:i:s" < current_time %}
        <a class="wrap_card" href="{% url 'idea:idea_detail' group_id=group.id idea_id=idea.id %}">
            <h3 class="card_title">{{ idea.title }}</h3>
            <!-- 투표 순위 표시 로직 -->
            {% if ideas_votes %}
            
              {% if idea.id == ideas_votes.idea_vote1_id %}
              <div><span class="cta_blue_badge">1지망</span></div>  
              {% elif idea.id == ideas_votes.idea_vote2_id %}
              <div><span class="cta_blue_badge">2지망</span></div>  
              {% elif idea.id == ideas_votes.idea_vote3_id %}
              <div><span class="cta_blue_badge">3지망</span></div>  
              {% endif %}
            
            {% endif %}
            <span class="inner_card_contents">{{ idea.intro }}</span>
            <span>{{idea.author}}</span>
        </a>
      {% else %}
        <a class="wrap_card" href="{% url 'idea:idea_detail' group_id=group.id idea_id=idea.id %}">
          <h3 class="card_title">{{ idea.title }}</h3>
          <!-- 투표 표시 로직 -->
          {% if idea.id == ideas_votes.idea_vote1_id or idea.id == ideas_votes.idea_vote2_id or idea.id == ideas_votes.idea_vote3_id or idea.id == ideas_votes.idea_vote4_id or idea.id == ideas_votes.idea_vote5_id or idea.id == ideas_votes.idea_vote6_id or idea.id == ideas_votes.idea_vote7_id or idea.id == ideas_votes.idea_vote8_id or idea.id == ideas_votes.idea_vote9_id or idea.id == ideas_votes.idea_vote10_id %}
            <div><span class="cta_blue_badge">선택</span></div>   
          {% endif %}
          
          <span class="inner_card_contents">{{ idea.intro }}</span>
          <span>{{idea.author}}</span>
        </a>
      {% endif %}
      {% endfor %}

      </div>
      
    {% endif %}
</section>

<script src={% static "js/main_page_time.js" %}  ></script>
{% endblock %}

MakeMate-main/templates/group/group_first_vote_create.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<h1>아이디어 투표하기</h1>

<form method="post">
  {% csrf_token %}
    {% for i in range %}
        <h2>{{ forloop.counter }}지망 아이디어 선택</h2>
        <select id="idea_vote{{ forloop.counter }}" name="idea_vote{{ forloop.counter }}" onchange="updateDropdowns()">
            <option value="" selected disabled>아이디어 선택</option>
            <option value="">선택 취소</option>
            {% for idea in ideas_for_voting %}
                <option value="{{ idea.id }}">{{ idea.title }}</option>
            {% endfor %}
        </select>
    {% endfor %}

  <button type="submit">투표하기</button>
</form>

<a href="{% url 'group:group_detail' group_id=group.id %}" class="btn">이전</a>

<script src="{% static 'js/group_dropdowns.js' %}"></script>
{% endblock %}

MakeMate-main/templates/group/group_idea_create.html
{% extends 'base.html' %} {% block head %}
<title>idea_create</title>
{% endblock %} {% block content %}
<section>
    <div class="wrap_title">
      <a href="{% url 'group:group_detail' group_id=group.id %}" class="home_btn">Home</a>
      <div class="inner_title">
        <h3 class="title_content">아이디어 추가하기</h3>
        <p class="subtitle_content">{{ group.title }}</p>
      </div>
    </div>

    <form action="{% url 'idea:idea_create' group_id=group.id %}" method="post" enctype="multipart/form-data" class="wrap_form" novalidate>
      <div id="vote_modify_form_container">
        {% csrf_token %}
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="wrap_error">
                {{ error }}
              </div>
              {% endfor %}
          {% endif %}
            <div id="vote_modify_form_container">
              <span>제목 <i class="form_highlight_content">*</i></span>
              {{ form.title }}
            </div>
            {% if form.title.errors %}
              {% for error in form.title.errors %}
              <div class="wrap_error">{{ error }}</div>
              {% endfor %}
            {% endif %}
            <div id="vote_modify_form_container">
              <span>한 줄 소개 <i class="form_highlight_content">*</i></span>
              {{ form.intro }}
              <div class="wrap_error">50자 미만으로 작성해주세요.</div>         
            </div>
            {% if form.intro.errors %}
              {% for error in form.intro.errors %}
              <div class="wrap_error">{{ error }}</div>
              {% endfor %}
            {% endif %}
            <div id="vote_modify_form_container">
              <span>첨부파일</span>
              {{ form.file }}        
            </div>
            {% if form.file.errors %}
              {% for error in form.file.errors %}
              <div class="wrap_error">{{ error }}</div>
              {% endfor %}
            {% endif %}
            <div id="vote_modify_form_container">
              <span>내용</span>
              {{ form.content }}        
            </div>
            {% if form.content.errors %}
              {% for error in form.content.errors %}
              <div class="wrap_error">{{ error }}</div>
              {% endfor %}
            {% endif %}
      </div>

      <div class="vote_create_btns">
        <button type="submit" class="primary_button_fill">저장하기</button>
        <!-- 홈으로 버튼에 URL 추가 필요 -->
      </div>
    </form>
</section>
{% endblock %}

MakeMate-main/templates/group/group_idea_detail.html
{% extends "base.html" %} 
{% load static %} 
{% block content %}
{% now "Y-m-d H:i:s" as current_time %}
<section>
    <div class="wrap_title">
      <a href="{% url 'group:group_detail' group_id=group.id %}" class="back_btn">back</a>
      <h3 class="title_content">{{ group.title }}</h3> 
      <div class="inner_title">
        <div class="title_with_badge">
          <div class="subtitle_content">{{ idea.title }}</div>
        {% if group.second_end_date|date:"Y-m-d H:i:s" < current_time %}
          {% if ideas_votes %} 
            {% if idea.id == ideas_votes.idea_vote1_id %}
              <span class="badge_idea_detail">1지망</span>
            {% elif idea.id == ideas_votes.idea_vote2_id %}
              <span class="badge_idea_detail">2지망</span>
            {% elif idea.id == ideas_votes.idea_vote3_id %}
              <span class="badge_idea_detail">3지망</span>
            {% endif %} 
          {% endif %}
        {% else %}
        {% if idea.id == ideas_votes.idea_vote1_id or idea.id == ideas_votes.idea_vote2_id or idea.id == ideas_votes.idea_vote3_id or idea.id == ideas_votes.idea_vote4_id or idea.id == ideas_votes.idea_vote5_id or idea.id == ideas_votes.idea_vote6_id or idea.id == ideas_votes.idea_vote7_id or idea.id == ideas_votes.idea_vote8_id or idea.id == ideas_votes.idea_vote9_id or idea.id == ideas_votes.idea_vote10_id %}
          <span class="cta_blue_badge">선택</span>
        {% endif %}
        {% endif %}
        </div>
        <div class="inner_idea_intro">
          <span>{{ idea.intro }}</span>
        </div>
        {% if idea.file %}
          <div class="wrap_download">
            <span class="download_content">발표자료 다운로드</span>
            <form action="{% url 'idea:idea_download' group_id=group.id idea_id=idea.id %}" class="secondary_badge">
              {% csrf_token %}
              <button>다운로드</button>
            </form>
          </div>
        {% endif %}
        </div>
        {% if idea.author == request.user %} 
        <div class="idea_detail_modify_btns">
          <form action="{% url 'idea:idea_delete' group_id=group.id idea_id=idea.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="action" value="delete">
            <button type="submit" class='cta_del_button'>삭제</button>
          </form>
          
          <a href="{% url 'idea:idea_modify' group_id=group.id idea_id=idea.id %}" class="primary_button_fill">내용 수정</a>
        </div>
        {% endif %}
    </div>
    <div class="wrap_form">  
        <div>{{ idea.content|linebreaks }}</div>      
    </div>
</section>

{% endblock %}

MakeMate-main/templates/group/group_idea_modify.html
{% extends 'base.html' %} {% block content %}
<section>
  <div class="wrap_title">
    <a href="{% url 'group:group_detail' group_id=group.id %}" class="home_btn">Home</a>
    <div class="inner_title">
      <h3 class="title_content">아이디어 수정하기</h3>
      <p class="subtitle_content">{{ group.title }}</p>
    </div>
  </div>

  <form
  action="{% url 'idea:idea_modify' group_id=group.id idea_id=idea.id %}"
  method="post"
  enctype="multipart/form-data"
  class="wrap_idea_modify_form"
  novalidate>
  <div id="vote_modify_form_container">
    {% csrf_token %}
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
    <div class="wrap_error">{{ error }}</div>
      {% endfor %}
    {% endif %}
    <div id="vote_modify_form_container">제목 <input type="text" name="title" value="{{idea.title}}" maxlength="31" required="" id="id_title" /></div>

    <div id="vote_modify_form_container">
      한 줄 소개 <input type="text" name="intro" value="{{idea.intro}}" maxlength="50" required="" id="id_intro" />
      <div class="wrap_error">50자 미만으로 작성해주세요.</div>
    </div>

    <div id="vote_modify_form_container">
      <div class="wrap_download">
        <span class="download_content">첨부파일</span>
        {% if idea.file %}
        <span>
          <span class="idea_file">{{ idea.file }}</span> 
        </span>
        {% else %}
        <span>첨부파일이 없습니다.</span>
        {% endif %}
        <br />
        변경
        <input type="file" name="file" id="id_file" />
      </div>
    </div>
    

    <div id="vote_modify_form_container">
      내용 <textarea name="content" cols="40" rows="10" maxlength="1000" required="" id="id_content">{{idea.content}}</textarea>
    </div>
  </div>

  <div class="vote_create_btns">
    <button type="submit" class="primary_button_fill">저장하기</button>
  </div>
</form>

</section>



{% endblock %}

MakeMate-main/templates/group/group_nonadmin_certification.html
{% extends 'base.html' %}
{% block content %}
<section>
    <div class="wrap_title">
        <a href="{% url 'common:main_page' %}" class='home_btn'>Home</a>
        <div class="inner_title">
            <h3 class="title_content">{{group.title}}</h3>
            <span class="subtitle_content">그룹 가입하기 (참가자)</span>
        </div>
    </div>
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div class="form_highlight_content">
        {{ error }}
    </div>
    {% endfor %}
    <form method='post' action={% url 'group_setting:check_nonadmin' group_id=group.id %} class="wrap_form" novalidate>
        {% csrf_token %}
        <div class="inner_form">
            <label>비밀번호를 입력해주세요.</label>
            <div>{{form.password}}</div>
            <!-- 필드 오류 -->
            {% if is_wrong %}
            <div class="form_highlight_content">
                비밀번호가 일치하지 않습니다. 다시 입력해주세요.
            </div>
            {% endif %}
        </div>
        <div class="inner_form_button">
            <button type='submit' class='primary_button_fill'>그룹 가입</button>
        <div>
    </form>
 
</section>
{% endblock %}