MakeMate-main/apps/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import main_page, signup, logout_page

app_name = "common"

urlpatterns = [
    path("", main_page, name="main_page"),
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", logout_page, name="logout"),
]

MakeMate-main/apps/idea/urls.py
from django.urls import path
from .views import *

app_name = "idea"

urlpatterns = [
    path("<int:group_id>/create/", idea_create, name="idea_create"),
    path("<int:group_id>/modify/<int:idea_id>/",
         idea_modify,
         name="idea_modify"),
    path("<int:group_id>/delete/<int:idea_id>/",
         idea_delete,
         name="idea_delete"),
    path("<int:group_id>/detail/<int:idea_id>/",
         idea_detail,
         name="idea_detail"),
    path(
        "<int:group_id>/download/<int:idea_id>/",
        idea_download,
        name="idea_download",
    ),
]

MakeMate-main/apps/preresult/urls.py
from django.urls import path
from .views import *

app_name = "preresult"

urlpatterns = [
    path("<int:group_id>/admin/", preresult, name="preresult"),
    path("<int:group_id>/", member_preresult, name="member_preresult"),
    path(
        "<int:group_id>/admin/modify",
        preresult_modify,
        name="preresult_modify",
    ),
    path(
        "<int:group_id>/admin/vote1/preresult/select",
        first_vote_select,
        name="first_vote_select",
    ),
    path(
        "<int:group_id>/admin/vote1/preresult/unselect",
        first_vote_unselect,
        name="first_vote_unselect",
    ),
    path(
        "<int:group_id>/admin/vote2/preresult/select",
        second_vote_select,
        name="second_vote_select",
    ),
    path(
        "<int:group_id>/admin/vote2/preresult/unselect",
        second_vote_unselect,
        name="second_vote_unselect",
    ),
]

MakeMate-main/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("group/", include("apps.group.urls")),
    path("group_admin/", include("apps.groupAdmin.urls")),
    path("setting/", include("apps.groupSetting.urls")),
    path("preresult/", include("apps.preresult.urls")),
    path("result/", include("apps.result.urls")),
    path("idea/", include("apps.idea.urls")),
    path("vote/", include("apps.vote.urls")),
]

MakeMate-main/apps/preresult/models.py
from django.db import models

# Create your models here.

MakeMate-main/apps/preresult/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
from apps.group.models import Group, MemberState, Idea, Vote
from apps.group.views import State, TeamNumber, redirect_by_auth


# Create your views here.
@login_required(login_url="common:login")
def preresult(request, group_id):
    # 그룹에 있는 아이디어를 모두 가져오고, 이를 투표점수 순서로 정렬
    # 그리고 동점자 처리도 해야하는데 그건 추후 다같이 결정
    group = Group.objects.get(id=group_id)
    members = MemberState.objects.filter(group=group)
    state = redirect_by_auth(request.user, group_id)
    current_time = timezone.now()
    if (current_time >= group.third_end_date
            and group.is_second_end == True):  # 세번째 임시결과 페이지
        if state == State.ADMIN:
            if request.method == "POST":
                group.is_third_end = True
                group.save()
                return redirect("result:result", group_id=group.id)
            else:
                idea_list = Idea.objects.filter(
                    group=group, second_selected=True).order_by("-votes")
                ctx = {
                    "idea_list": idea_list,
                    "members": members,
                    "group": group
                }
                return render(request,
                              "preresult/preresult_admin.html",
                              context=ctx)
        else:
            return redirect("/")
    elif (current_time >= group.second_end_date
          and group.is_first_end == True):  # 두번째 임시결과 페이지
        if state == State.ADMIN:
            if request.method == "POST":
                group.is_second_end = True
                group.save()
                reset_idea = Idea.objects.all()
                reset_vote(reset_idea)
                return redirect("/")
            else:
                second_top_selected(group, 5)
                idea_list = Idea.objects.filter(
                    group=group, is_selected=True).order_by("-votes")
                ctx = {"idea_list": idea_list, "group": group}
                return render(request,
                              "preresult/preresult_second_vote_select.html",
                              context=ctx)
        else:
            return redirect("/")
    elif current_time >= group.first_end_date:  # 첫번째 임시결과 페이지
        if state == State.ADMIN:
            if request.method == "POST":
                group.is_first_end = True
                group.save()
                reset_idea = Idea.objects.all()
                reset_vote(reset_idea)
                return redirect("/")
            else:
                top_selected(group, 10)
                idea_list = Idea.objects.filter(group=group).order_by("-votes")
                ctx = {"group": group, "idea_list": idea_list}
                return render(
                    request,
                    "preresult/preresult_first_vote_select.html",
                    context=ctx,
                )
        else:
            return redirect("/")
    else:
        redirect_url = reverse("group:group_detail",
                               kwargs={"group_id": group_id})
        return redirect(redirect_url)


@login_required(login_url="common:login")
def member_preresult(request, group_id):
    group = Group.objects.get(id=group_id)
    idea_list = Idea.objects.filter(group=group, second_selected=True).order_by("-votes")
    user_state = MemberState.objects.filter(user=request.user,
                                            group=group).first()
    state = redirect_by_auth(request.user, group_id)

    current_time = timezone.now()
    if current_time >= group.third_end_date:
        if state == State.WITH_HISTORY or state == State.ADMIN:
            ideas_votes = {}
            if user_state:
                ideas_votes["idea_vote1_id"] = (user_state.idea_vote1.id
                                                if user_state.idea_vote1 else
                                                None)
                ideas_votes["idea_vote2_id"] = (user_state.idea_vote2.id
                                                if user_state.idea_vote2 else
                                                None)
                ideas_votes["idea_vote3_id"] = (user_state.idea_vote3.id
                                                if user_state.idea_vote3 else
                                                None)
            ctx = {
                "group": group,
                "idea_list": idea_list,
                "ideas_votes": ideas_votes,
            }

            return render(request, "preresult/preresult_member.html", ctx)
        else:
            return redirect("/")
    elif current_time >= group.second_end_date and group.is_first_end == True:
        if state == State.WITH_HISTORY or state == State.ADMIN:
            ideas_votes = {}

            ctx = {
                "group": group,
                "idea_list": idea_list,
                "ideas_votes": ideas_votes,
            }

            return render(request, "preresult/preresult_member.html", ctx)
        else:
            return redirect("/")
    elif current_time >= group.first_end_date:
        if state == State.WITH_HISTORY or state == State.ADMIN:
            ideas_votes = {}

            ctx = {
                "group": group,
                "idea_list": idea_list,
                "ideas_votes": ideas_votes,
            }

            return render(request, "preresult/preresult_member.html", ctx)
        else:
            return redirect("/")
    else:
        redirect_url = reverse("group:group_detail",
                               kwargs={"group_id": group_id})
        return redirect(redirect_url)


@login_required(login_url="common:login")
def preresult_modify(request, group_id):
    group = Group.objects.get(id=group_id)
    idea_list = Idea.objects.filter(
        group=group, second_selected=True).order_by("-votes")
    members = MemberState.objects.filter(group=group,
                                         group_ability__isnull=False)
    state = redirect_by_auth(request.user, group_id)

    current_time = timezone.now()
    if current_time >= group.third_end_date:
        if state == State.ADMIN:
            if request.method == "POST":
                selected_values = request.POST.get("team_modify").split(",")
                member_id = int(selected_values[0])
                idea_id = int(selected_values[1])
                mod_mem = MemberState.objects.get(id=member_id)
                prev_idea = mod_mem.my_team_idea
                mod_idea = Idea.objects.get(id=idea_id)

                # (전제)팀장은 수정 페이지에서 팀 변경되면 안됨. 함수 실행X 바로 리디렉션
                for idea in idea_list:
                    if idea.author == mod_mem.user:
                        url = reverse("preresult:preresult", args=[group.id])
                        return redirect(url)

                # (수정과정1)전에 있던 아이디어의 멤버에서 해당 멤버스테이트의 유저를 지움(수정한 아이디어의 멤버를 추가하기 위해서)
                if prev_idea != mod_idea:
                    prev_idea.member.remove(mod_mem.user)
                    prev_idea.save()
                # (수정과정2)해당 멤버스테이트의 최종 팀을 수정한 아이디어의 팀으로 설정
                mod_mem.my_team_idea = mod_idea
                mod_mem.save()
                # (수정과정3)수정한 아이디어의 멤버에 해당 멤버스테이트의 유저를 추가.
                mod_idea.member.add(mod_mem.user)
                mod_idea.save()

                url = reverse("preresult:preresult", args=[group.id])
                return redirect(url)
            else:
                ctx = {
                    "members": members,
                    "idea_list": idea_list,
                    "group": group,
                }
                return render(request,
                              "preresult/preresult_modify.html",
                              context=ctx)
        else:
            return redirect("/")
    else:
        redirect_url = reverse("group:group_detail",
                               kwargs={"group_id": group_id})
        return redirect(redirect_url)


def calculate_first_idea_scores(group_id):
    ideas = Idea.objects.filter(group_id=group_id)

    for idea in ideas:
        votes_count = (MemberState.objects.filter(group_id=group_id).filter(
            Q(idea_vote1=idea)
            | Q(idea_vote2=idea)
            | Q(idea_vote3=idea)
            | Q(idea_vote4=idea)
            | Q(idea_vote5=idea)
            | Q(idea_vote6=idea)
            | Q(idea_vote7=idea)
            | Q(idea_vote8=idea)
            | Q(idea_vote9=idea)
            | Q(idea_vote10=idea)).count())

        idea.votes = votes_count

        # 투표 초기화
        idea.idea_vote1_set.clear()
        idea.idea_vote2_set.clear()
        idea.idea_vote3_set.clear()
        idea.idea_vote4_set.clear()
        idea.idea_vote5_set.clear()
        idea.idea_vote6_set.clear()
        idea.idea_vote7_set.clear()
        idea.idea_vote8_set.clear()
        idea.idea_vote9_set.clear()
        idea.idea_vote10_set.clear()

        idea.save()

    user_state_list = MemberState.objects.filter(group_id=group_id)


def calculate_second_idea_scores(group_id):
    ideas = Idea.objects.filter(group_id=group_id)

    for idea in ideas:
        votes_count = (MemberState.objects.filter(group_id=group_id).filter(
            Q(idea_vote1=idea)
            | Q(idea_vote2=idea)
            | Q(idea_vote3=idea)
            | Q(idea_vote4=idea)
            | Q(idea_vote5=idea)).count())

        idea.votes = votes_count

        # 투표 초기화
        idea.idea_vote1_set.clear()
        idea.idea_vote2_set.clear()
        idea.idea_vote3_set.clear()
        idea.idea_vote4_set.clear()
        idea.idea_vote5_set.clear()

        idea.save()


def calculate_third_idea_scores(group_id):
    ideas = Idea.objects.filter(group_id=group_id)

    for idea in ideas:

MakeMate-main/templates/preresult/preresult_admin.html
{% extends 'base.html' %}

{% block content %}
<section>
        <div class="wrap_title">
            <a href="{% url 'common:main_page' %}" class='home_btn'>back</a>
            <div class="inner_title">
                <p class="preresult_title">{{group.title}}</p>
                <span>결과가 임시발표되었습니다. 내용을 수정한 뒤 전체 구성원에게 공지할 수 있습니다.</span>
            </div>
            <div class="preresult_btns">
                <form method='post' action="{%url 'preresult:preresult' group.id%}">
                    {% csrf_token %}
                    <button class='secondary_button'>발표하기</button>
                </form>
                <button class="primary_button"><a href="{% url 'preresult:preresult_modify' group.pk %}">팀 정보 수정하기</a></button>
            </div>
        </div>
        <div class="preresult_admin_body_container">
            <h1>임시 팀빌딩 결과</h1>
            <div class="wrap_wrap_card">
            {% for idea in idea_list %}
                <div class="wrap_card">
                    <h2 class="choice_idea_title">{{idea.title}}</h2>
                    <p class="choice_intro_title">{{idea.intro}}</p>

                        <div class="inner_card_badge">
                            <span>팀장</span>
                            <span class="primary_badge">{{idea.author.username}}</span>
                        </div>
                        <div class="inner_title">
                            <p>전체 팀원</p>
                            <div class="preresult_admin_member_list">
                                {% for member in idea.member.all %}
                                    <div class="cta_blue_badge">{{member.username}}</div>
                                {% endfor %}
                            </div>
                        </div>

                </div>
            {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

MakeMate-main/templates/preresult/preresult_first_vote_select.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section>
      <div class='home_btn'><a href="{%url 'common:main_page'%}">Home</a></div>
      <div class='wrap_title'>
          <div class="inner_title">
            <span class='title_content'>{{group.title}}</span>
            <span class="subtitle_content">1차 투표 임시 결과</span>
          </div>
          <div>투표 결과가 발표되었습니다. 1차 아이디어 선정을 수정한뒤 전체 구성원에게 공지 할 수 있습니다.</div>
      </div>
      <p class='preresult_vote1_select'>1차 아이디어 선정</p>
      <div class="wrap_wrap_card">
        {% for idea in idea_list  %}
          <div class='preresult_vote1_inner_idea'>
            <div class='prereuslt_vote1_idea_title'><a href={% url "idea:idea_detail" group.id idea.id%}>{{idea.title}}</a></div>
            <div>
              <div>{{idea.intro}}</div>
              <div class='card_contents_green'>{{idea.author}}</div>
            </div>
            <div class='prerrsult_vote1_select_btn'>
              <div>score: {{idea.votes}}</div>
              {% if idea.is_selected %}
                <button class='cta_blue_badge' data-idea-id="{{idea.id}}">선택</button>
              {% else %}
              <button class='cta_red_badge' data-idea-id="{{idea.id}}">선택</button>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
      <form method='post' action="{%url 'preresult:preresult' group.id%}" class="inner_form_button">
          {% csrf_token %}
          <button class='primary_button_fill'>발표하기</button>
      </form>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static "js/first_vote_selecte.js" %}"></script>
{% endblock content %}

MakeMate-main/templates/preresult/preresult_member.html
{% extends 'base.html' %}
{% block content %}
{% now "Y-m-d H:i:s" as current_time %}
<section>
        <div class="preresult_member_header_container">
            <div class="preresult_member_description">
                <a href="{% url 'common:main_page' %}" class='home_btn'>back</a>
                <p class="preresult_member_title">{{group.title}}</p>
                {% if group.third_end_date|date:"Y-m-d H:i:s" < current_time %}
                <span>3차 투표가 종료되었습니다. 운영진이 결과를 발표할 때까지 기다려주세요.</span>
                {% elif group.second_end_date|date:"Y-m-d H:i:s" < current_time %}
                <span>2차 투표가 종료되었습니다. 운영진이 결과를 발표할 때까지 기다려주세요.</span>
                {% else %}
                <span>1차 투표가 종료되었습니다. 운영진이 결과를 발표할 때까지 기다려주세요.</span>                               
                {% endif %}
            </div>
        </div>

        {% if idea_list %}
        <h2>투표</h2>
        <div class="preresult_member_idea">
            {% for idea in idea_list %}
            <div class="preresult_member_idea_desc">
                <h3>
                <a href="{% url 'idea:idea_detail' group_id=group.id idea_id=idea.id %}">
                    {{ idea.title }}
                </a>
                </h3>
                <!-- 투표 순위 표시 로직 -->
                {% if ideas_votes %}
                    {% if idea.id == ideas_votes.idea_vote1_id %} 
                    <p class="preresult_member_vote_badge">1지망</p>
                    {% elif idea.id == ideas_votes.idea_vote2_id %} 
                    <p class="preresult_member_vote_badge">2지망</p>
                    {% elif idea.id == ideas_votes.idea_vote3_id %} 
                    <p class="preresult_member_vote_badge">3지망</p>
                    {% endif %}
                {% endif %}
                <p class="idea_desc_content">{{ idea.content }}</p>
                <span>{{idea.author}}</span>
            </div>
            {% endfor %}
        </div>
        {% endif %}

</section>
{% endblock content %} 

MakeMate-main/templates/preresult/preresult_modify.html
{% extends 'base.html' %}

{% block content %}
<section>
        <div class="preresult_admin_header_container">
            <div class="preresult_admin_description">
                <a href="{% url 'common:main_page' %}" class='home_btn'>back</a>
                <p class="preresult_title">{{group.title}}</p>
                <span>팀 정보를 수정할 수 있는 페이지입니다. 저장하기를 누르지 않으면 변경 사항이 저장되지 않습니다.</span>
            </div>
            <button id="result_home_button" class="primary_button"><a href="/">홈으로</a></button>
        </div>
        <div class="preresult_admin_body_container">
            <h1>회원</h1>
            <div class="preresult_modify_container">
                {% for member in members %}
                    <div class="group_preresult_modify_container">
                        <div class="preresult_modify_member_title">
                            <h2>{{member.user.username}}</h2>
                            <span class="secondary_badge">{{member.my_team_idea}}</span>
                        </div>
                        <!-- 생각해보니 여기도 동적으로 만들어야 하는데 3지망 고정값으로 만들면 안되네요;; -->
                        <!-- 근데 db모델부터 3개 하드코딩으로 박혀있네....? 일단 패스-->
                        <div class="preresult_modify_choice_team">
                            {% if member.idea_vote1 %}
                            <p>1지망 : {{member.idea_vote1}}</p>
                            <p>2지망 : {{member.idea_vote2}}</p>
                            <p>3지망 : {{member.idea_vote3}}</p>
                            {% else %}
                            <p>투표에 참여하지 않은 회원입니다.</p>
                            {% endif %}
                        </div>
                        <h2>팀 변경</h2>
                        <form class="preresult_modify_save" action="{% url 'preresult:preresult_modify' group.pk %}" method="post">
                            {% csrf_token %}
                            <select name="team_modify">
                                <option value="{{member.id}},{{member.my_team_idea.id}}">{{member.my_team_idea.title}}</option>
                                {% for idea in idea_list %}
                                    <option value="{{member.id}},{{idea.id}}">{{idea.title}}</option>
                                {% endfor %}
                            </select>
                            <button class="primary_button">저장하기</button>
                        </form>
                    </div>
                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

MakeMate-main/templates/preresult/preresult_second_vote_select.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <section>
      <div class='home_btn'><a href="{%url 'common:main_page'%}">Home</a></div>
      <div class='wrap_title'>
        <div class='inner_title'>
          <span class='title_content'>{{group.title}}</div>
          <span class="subtitle_content">2차 투표 임시 결과</div>
        </div>
        <span>투표 결과가 발표되었습니다. 최종 아이디어 선정을 수정한뒤 전체 구성원에게 공지 할수있습니다</span>
      </div>
      <div class='preresult_vote1_select'>최종 아이디어 선정</div>
      <div class="wrap_wrap_card">
        {% for idea in idea_list  %}
          <div class='wrap_card'>
            <div class='prereuslt_vote1_idea_title'><a href={% url "idea:idea_detail" group.id idea.id%}>{{idea.title}}</a></div>
            <div>
              <span>{{idea.intro}}</span>
              <div class='card_contents_green'>{{idea.author}}</div>
            </div>
            <div class='prerrsult_vote1_select_btn'>
              <div>score: {{idea.votes}}</div>
              {% if idea.second_selected %}
                <button class='cta_blue_badge' data-idea-id="{{idea.id}}">선택</button>
              {% else %}
              <button class='cta_red_badge' data-idea-id="{{idea.id}}">선택</button>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
      <form method='post' action="{%url 'preresult:preresult' group.id%}" class="inner_form_button">
        {% csrf_token %}
        <button class='primary_button_fill'>발표하기</button>
      </form>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="{% static "js/second_vote_select.js" %}"></script>
{% endblock content %}